### PR TITLE
Skip to next source if a source responds with 404

### LINKED ISSUE #31: WebLoader does not try next source if request returns a 404 response
### Expected Behavior

If an asset request returns a 404 response the WebLoader should skip that source and try the next.

### Actual Behavior

The 404 response body is returned.

### Steps to Reproduce

```
class Storage extends ScratchStorage {
    constructor () {
        super();
        this.addWebSource(
            [this.AssetType.Project],
            asset => `https://example.com/${asset.assetId}`
        );
    }
}

const storage = new Storage();
storage.load(storage.AssetType.Project, "x", storage.DataFormat.JSON)
    .then(project => console.log("I did load this:", project))
    .catch(e => console.error("Loading failed"));
```

---

I'll try to submit a PR for this.

### PR DESCRIPTION
**Pull request by mraerino**
### Resolves

Fixes #31

### CODE REVIEW

File: src/WebHelper.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ class WebHelper extends Helper {
 
                     nets({url: url}, (err, resp, body) => {
                         // body is a Buffer
-                        if (err) {
+                        if (err || String(resp.statusCode).substr(0, 1) !== '2') {
```
Comment (cwillisf) [inline src/WebHelper.js]: I like the idea but I would prefer not to convert the integer into a `String`. How about either:
- check if `resp.statusCode` is between 200 and 299, inclusive, or
- check if the integer part of `resp.statusCode / 100` is exactly 2

Comment (mraerino) [reply src/WebHelper.js]: @cwillisf I fixed this 🙂
